### ISSUE TITLE
Provide the html documentation to developers

### ISSUE THREAD

**Issue by ahaselsteiner** [ahaselsteiner/virocon#24]
A link to the html documentation should be added in README.md and in the app, probably at "About" or "Help".

- [x] make docs available online
- [x] keep docs up to date automatically
- [x] add link in README.md
- [x] add link in "About" or "Help"

**Comment by kawindme** [comment]
I would suggest using github pages to host the documentation. There are three possible locations to store the docs:
- directly in the master branch
- a /docs folder in master branch
- a branch called gh-pages

The website will then be accessible at [https://ahaselsteiner.github.io/virocon](https://ahaselsteiner.github.io/virocon)

I would suggest using the separate gh-pages branch, because i think it might then be possbile to automate the docs building process.

**Comment by kawindme** [comment]
I just created the gh-pages branch and pushed the docs. @ahaselsteiner can you please follow [this](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages) tutorial to make github pages use the gh-pages branch?

**Comment by ahaselsteiner** [comment]
It works, this is awesome!

It was already set as described in the tutorial. @kawindme did you change that? Or did this happen automatically?

I added the link to the README.md

**Comment by kawindme** [comment]
Great! 
I didn't change anything after pushing to gh-pages. I guess it just took some time to process.

**Comment by kawindme** [comment]
Merge of branch Issue#24-deploy-docu completes this.
